{
    "name": "IPAI Scout Brand Detection",
    "summary": "Brand vision ingestion, shelf metrics, and market competitiveness for Scout retail analytics.",
    "version": "18.0.2.0.0",
    "author": "InsightPulseAI",
    "license": "AGPL-3",
    "category": "Sales/Analytics",
    "depends": [
        "base",
        "product",
        "product_brand",
        "ipai_scout_retail_core",
        "ipai_ai_recommendation",
    ],
    "data": [
        "security/ipai_scout_brand_detection_groups.xml",
        "security/ipai_scout_brand_detection_security.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/cron_market.xml",
        "views/ipai_store_structure_views.xml",
        "views/ipai_brand_detection_views.xml",
        "views/ipai_shelf_brand_metric_views.xml",
        "views/ipai_ai_recommendation_views.xml",
        "views/ipai_brand_feedback_views.xml",
        "views/ipai_market_competition_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
